'use strict';
/* FinFlow v1: all records stay in browser localStorage; no network activity. */
const STORAGE_KEY = 'finflowBudgetPlannerV1';
const DEFAULT_CATEGORIES = [
  { id: 'housing', name: 'Housing', type: 'expense' }, { id: 'groceries', name: 'Groceries', type: 'expense' },
  { id: 'transportation', name: 'Transportation', type: 'expense' }, { id: 'utilities', name: 'Utilities', type: 'expense' },
  { id: 'health', name: 'Health', type: 'expense' }, { id: 'personal', name: 'Personal', type: 'expense' },
  { id: 'salary', name: 'Salary', type: 'income' }, { id: 'other-income', name: 'Other income', type: 'income' }
];
const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];
let state = loadState();
let activeView = 'dashboard';

function defaultState() { return { version: 1, transactions: [], categories: structuredClone(DEFAULT_CATEGORIES), budgets: {}, goals: [] }; }
function loadState() {
  try {
    const saved = localStorage.getItem(STORAGE_KEY);
    if (!saved) return defaultState();
    const candidate = JSON.parse(saved);
    if (!validateBackup(candidate)) throw new Error('Saved FinFlow data has an unsupported format.');
    return candidate;
  } catch (error) { console.error(error); announce('Saved data could not be read. A new empty planner was opened.'); return defaultState(); }
}
function saveState(message) { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); if (message) announce(message); render(); }
function validateBackup(data) { return data && data.version === 1 && Array.isArray(data.transactions) && Array.isArray(data.categories) && data.budgets && Array.isArray(data.goals); }
function announce(message) { const el = $('#status'); el.textContent = ''; setTimeout(() => { el.textContent = message; }, 50); }
function uid(prefix) { return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`; }
function escapeHtml(value) { const div = document.createElement('div'); div.textContent = String(value || ''); return div.innerHTML; }
function money(value) { return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(Number(value) || 0); }
function monthKey() { return $('#monthPicker').value || new Date().toISOString().slice(0, 7); }
function friendlyMonth(key) { return new Date(`${key}-01T12:00:00`).toLocaleDateString(undefined, { month: 'long', year: 'numeric' }); }
function sameMonth(date, month) { return String(date).slice(0, 7) === month; }
function openDialog(id) { const dialog = $(`#${id}`); dialog.showModal(); const first = dialog.querySelector('input,select,button'); if (first) first.focus(); }
function closeDialog(id) { $(`#${id}`).close(); }
function currentMonthTransactions() { const month = monthKey(); return state.transactions.filter((item) => sameMonth(item.date, month)); }
function totalsForMonth(month) { const items = state.transactions.filter((item) => sameMonth(item.date, month)); return { income: items.filter(i => i.type === 'income').reduce((sum, i) => sum + i.amount, 0), expense: items.filter(i => i.type === 'expense').reduce((sum, i) => sum + i.amount, 0) }; }
function categoryById(id) { return state.categories.find(c => c.id === id); }
function categoryName(id) { const category = categoryById(id); return category ? category.name : 'Uncategorized'; }
function sortNewest(items) { return [...items].sort((a, b) => b.date.localeCompare(a.date) || b.createdAt - a.createdAt); }
function render() { syncMonthInputs(); renderDashboard(); renderTransactions(); renderBudgets(); renderGoals(); }
function syncMonthInputs() { const month = monthKey(); $('#monthPicker').value = month; $('#budgetMonthPicker').value = month; $('#monthHeading').textContent = friendlyMonth(month); }
function renderDashboard() {
  const month = monthKey(); const totals = totalsForMonth(month); const budgetAmount = Object.values(state.budgets[month] || {}).reduce((sum, val) => sum + (Number(val) || 0), 0);
  $('#incomeTotal').textContent = money(totals.income); $('#expenseTotal').textContent = money(totals.expense); $('#cashFlowTotal').textContent = money(totals.income - totals.expense);
  $('#remainingBudget').textContent = budgetAmount ? money(budgetAmount - totals.expense) : 'Not set'; $('#budgetHint').textContent = budgetAmount ? `${money(totals.expense)} of ${money(budgetAmount)} planned` : 'add category budgets to track it';
  const recent = sortNewest(state.transactions).slice(0, 5); $('#recentTransactions').innerHTML = recent.length ? recent.map(transactionRow).join('') : emptyInline('No activity recorded yet. Add a transaction to begin.');
  const goals = state.goals.slice(0, 4); $('#goalSnapshot').innerHTML = goals.length ? goals.map(goal => `<div class="list-row"><div><p><strong>${escapeHtml(goal.name)}</strong></p><p class="subtext">${money(goal.current)} of ${money(goal.target)}</p></div><strong>${Math.min(100, Math.round(goal.current / goal.target * 100))}%</strong></div>`).join('') : emptyInline('No savings goals yet. Create one when you are ready.');
}
function transactionRow(item) { return `<div class="list-row"><div><p><strong>${escapeHtml(item.description)}</strong></p><p class="subtext">${new Date(`${item.date}T12:00:00`).toLocaleDateString()} · ${escapeHtml(categoryName(item.categoryId))}</p></div><strong class="amount-${item.type}">${item.type === 'income' ? '+' : '−'}${money(item.amount)}</strong></div>`; }
function emptyInline(message) { return `<p class="subtext">${escapeHtml(message)}</p>`; }
function renderTransactions() {
  const query = $('#transactionSearch').value.trim().toLowerCase(); const type = $('#transactionType').value;
  const filtered = sortNewest(state.transactions).filter(item => (type === 'all' || item.type === type) && (!query || `${item.description} ${categoryName(item.categoryId)}`.toLowerCase().includes(query)));
  $('#transactionCount').textContent = `${filtered.length} ${filtered.length === 1 ? 'entry' : 'entries'}`;
  $('#transactionTable').innerHTML = filtered.map(item => `<tr><td>${escapeHtml(item.date)}</td><td>${escapeHtml(item.description)}</td><td>${escapeHtml(categoryName(item.categoryId))}</td><td><span class="amount-${item.type}">${item.type === 'income' ? 'Income' : 'Expense'}</span></td><td class="number ${item.type === 'income' ? 'amount-income' : 'amount-expense'}">${item.type === 'income' ? '+' : '−'}${money(item.amount)}</td><td><button class="action-button" data-edit-transaction="${item.id}" type="button" aria-label="Edit ${escapeHtml(item.description)}">Edit</button></td></tr>`).join('');
  $('#transactionEmpty').hidden = filtered.length !== 0;
}
function renderBudgets() {
  const month = monthKey(); const expenses = state.categories.filter(c => c.type === 'expense'); const monthBudgets = state.budgets[month] || {};
  $('#budgetEmpty').hidden = expenses.length !== 0; $('#budgetRows').innerHTML = expenses.map(category => {
    const budget = Number(monthBudgets[category.id]) || 0; const spent = state.transactions.filter(t => sameMonth(t.date, month) && t.type === 'expense' && t.categoryId === category.id).reduce((sum, t) => sum + t.amount, 0);
    const percent = budget ? Math.min(100, spent / budget * 100) : 0; const over = budget && spent > budget;
    return `<div class="budget-row"><div><div class="budget-name">${escapeHtml(category.name)}</div><div class="budget-spent">${money(spent)} spent${budget ? ` · ${money(Math.max(0, budget-spent))} remaining` : ' · no limit set'}</div></div><label>Monthly limit<input data-budget-category="${category.id}" type="number" min="0" step="0.01" inputmode="decimal" value="${budget || ''}" placeholder="0.00" aria-label="Monthly budget for ${escapeHtml(category.name)}"></label><div><div class="progress ${over ? 'over' : ''}" aria-label="${Math.round(percent)} percent of budget used"><span style="width:${percent}%"></span></div><div class="budget-spent">${budget ? `${Math.round(spent / budget * 100)}% used` : 'Optional budget'}</div></div></div>`;
  }).join('');
}
function renderGoals() {
  $('#goalsEmpty').hidden = state.goals.length !== 0;
  $('#goalsGrid').innerHTML = state.goals.map(goal => { const pct = Math.min(100, goal.current / goal.target * 100); return `<article class="goal-card"><h3>${escapeHtml(goal.name)}</h3><p>Saved toward target</p><strong>${money(goal.current)} <span class="subtext">/ ${money(goal.target)}</span></strong><div class="progress" aria-label="${Math.round(pct)} percent complete"><span style="width:${pct}%"></span></div><p>${Math.round(pct)}% complete · ${money(Math.max(0, goal.target-goal.current))} to go</p><div class="goal-actions"><button class="text-button" data-edit-goal="${goal.id}" type="button">Edit</button><button class="text-button" data-delete-goal="${goal.id}" type="button">Delete</button></div></article>`; }).join('');
}
function fillCategories(type, selected) { const select = $('#transactionCategory'); const items = state.categories.filter(c => c.type === type); select.innerHTML = items.length ? items.map(c => `<option value="${c.id}" ${c.id === selected ? 'selected' : ''}>${escapeHtml(c.name)}</option>`).join('') : '<option value="">No matching categories—add one first</option>'; }
function showTransaction(id) {
  const item = state.transactions.find(t => t.id === id); $('#transactionForm').reset(); $('#transactionId').value = item?.id || ''; $('#transactionDialogTitle').textContent = item ? 'Edit transaction' : 'Add transaction'; $('#transactionDate').value = item?.date || new Date().toISOString().slice(0, 10); $('#entryType').value = item?.type || 'expense'; fillCategories($('#entryType').value, item?.categoryId); $('#transactionDescription').value = item?.description || ''; $('#transactionAmount').value = item?.amount || ''; openDialog('transactionDialog');
}
function showGoal(id) { const goal = state.goals.find(g => g.id === id); $('#goalForm').reset(); $('#goalId').value = goal?.id || ''; $('#goalDialogTitle').textContent = goal ? 'Edit savings goal' : 'Add savings goal'; $('#goalName').value = goal?.name || ''; $('#goalTarget').value = goal?.target || ''; $('#goalCurrent').value = goal?.current ?? '0.00'; openDialog('goalDialog'); }
function renderCategoryManager() { $('#categoryList').innerHTML = state.categories.map(c => { const used = state.transactions.some(t => t.categoryId === c.id); return `<div class="category-row"><p><strong>${escapeHtml(c.name)}</strong> <span class="subtext">${c.type}</span></p>${used ? '<span class="subtext">In use</span>' : `<button class="text-button" data-delete-category="${c.id}" type="button">Delete</button>`}</div>`; }).join(''); }
function csvEscape(value) { const text = String(value ?? ''); return /[",\n]/.test(text) ? `"${text.replaceAll('"', '""')}"` : text; }
function download(name, contents, type) { const url = URL.createObjectURL(new Blob([contents], { type })); const a = document.createElement('a'); a.href = url; a.download = name; document.body.append(a); a.click(); a.remove(); setTimeout(() => URL.revokeObjectURL(url), 500); }
function exportCSV() { const header = ['date', 'description', 'amount', 'category', 'type']; const body = sortNewest(state.transactions).map(t => [t.date, t.description, t.amount.toFixed(2), categoryName(t.categoryId), t.type].map(csvEscape).join(',')); download(`finflow-transactions-${new Date().toISOString().slice(0,10)}.csv`, [header.join(','), ...body].join('\n'), 'text/csv;charset=utf-8'); announce('CSV export downloaded.'); }
function parseCSV(text) { const rows=[]; let row=[], field='', quote=false; for(let i=0;i<text.length;i++){const char=text[i], next=text[i+1]; if(char==='"'&&quote&&next==='"'){field+='"';i++;}else if(char==='"'){quote=!quote;}else if(char===','&&!quote){row.push(field.trim());field='';}else if((char==='\n'||char==='\r')&&!quote){if(char==='\r'&&next==='\n')i++;row.push(field.trim()); if(row.some(Boolean))rows.push(row);row=[];field='';}else field+=char;} row.push(field.trim());if(row.some(Boolean))rows.push(row); if(quote)throw new Error('CSV has an unmatched quotation mark.');return rows; }
function importCSV(file) { const reader = new FileReader(); reader.onload = () => { try { const rows = parseCSV(String(reader.result).replace(/^\uFEFF/, '')); if (rows.length < 2) throw new Error('The CSV needs a header row and at least one data row.'); const headers = rows[0].map(h => h.toLowerCase().trim()); const required = ['date','description','amount','category','type']; const missing = required.filter(h => !headers.includes(h)); if (missing.length) throw new Error(`Missing required header(s): ${missing.join(', ')}.`); const idx = Object.fromEntries(headers.map((h,i)=>[h,i])); const additions=[]; const newCategories=[]; const errors=[]; rows.slice(1).forEach((row,n)=>{ const line=n+2, date=row[idx.date], description=row[idx.description], amount=Number(row[idx.amount]), categoryNameInput=(row[idx.category]||'').trim(), type=(row[idx.type]||'').toLowerCase(); if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||Number.isNaN(Date.parse(`${date}T12:00:00`))) errors.push(`row ${line}: invalid date`); else if(!description||!Number.isFinite(amount)||amount<=0||!categoryNameInput||!['income','expense'].includes(type)) errors.push(`row ${line}: date, description, positive amount, category, and type (income/expense) are required`); else { let category=[...state.categories,...newCategories].find(c=>c.name.toLowerCase()===categoryNameInput.toLowerCase()&&c.type===type); if(!category){ category={id:uid('cat'),name:categoryNameInput.slice(0,40),type}; newCategories.push(category); } additions.push({id:uid('tx'),date,description:description.slice(0,120),amount,categoryId:category.id,type,createdAt:Date.now()+n}); } }); if(errors.length) throw new Error(`Nothing imported. Fix ${errors.length} issue(s): ${errors.slice(0,4).join('; ')}${errors.length>4?'…':''}`); state.categories.push(...newCategories); state.transactions.push(...additions); saveState(`${additions.length} transaction${additions.length===1?'':'s'} imported from CSV.`); } catch(error){console.error(error); announce(`Import failed: ${error.message}`); alert(`CSV import failed:\n\n${error.message}`); } finally { $('#csvImportInput').value=''; } }; reader.readAsText(file); }
function importJSON(file) { const reader=new FileReader(); reader.onload=()=>{try{const incoming=JSON.parse(String(reader.result));if(!validateBackup(incoming))throw new Error('This is not a compatible FinFlow v1 backup.');if(!confirm('Restore this backup? It will replace all current FinFlow data in this browser.'))return;state=incoming;saveState('Backup restored.');closeDialog('backupDialog');}catch(error){console.error(error);announce(`Restore failed: ${error.message}`);alert(`JSON restore failed:\n\n${error.message}`);}finally{$('#jsonImportInput').value='';}};reader.readAsText(file); }

$$('.tab').forEach(button => button.addEventListener('click', () => { activeView=button.dataset.view; $$('.tab').forEach(t=>{const is=t===button;t.classList.toggle('is-active',is);t.setAttribute('aria-selected',String(is));}); $$('.view').forEach(v=>v.hidden=v.id!==activeView); $(`#${activeView}`).focus?.(); }));
$('#monthPicker').value=new Date().toISOString().slice(0,7); $('#monthPicker').addEventListener('change', render); $('#budgetMonthPicker').addEventListener('change', e=>{$('#monthPicker').value=e.target.value;render();});
$('#showTransactionForm').addEventListener('click',()=>showTransaction()); $$('[data-open-transaction]').forEach(b=>b.addEventListener('click',()=>showTransaction())); $('#entryType').addEventListener('change',e=>fillCategories(e.target.value));
$('#transactionForm').addEventListener('submit',e=>{e.preventDefault();const id=$('#transactionId').value, type=$('#entryType').value, categoryId=$('#transactionCategory').value, amount=Number($('#transactionAmount').value);if(!categoryId||!Number.isFinite(amount)||amount<=0)return announce('Choose a category and enter an amount greater than zero.');const data={id:id||uid('tx'),date:$('#transactionDate').value,description:$('#transactionDescription').value.trim(),amount,categoryId,type,createdAt:id?(state.transactions.find(t=>t.id===id)?.createdAt||Date.now()):Date.now()};if(id)state.transactions=state.transactions.map(t=>t.id===id?data:t);else state.transactions.push(data);closeDialog('transactionDialog');saveState(id?'Transaction updated.':'Transaction added.');});
$('#transactionSearch').addEventListener('input',renderTransactions);$('#transactionType').addEventListener('change',renderTransactions);$('#transactionTable').addEventListener('click',e=>{const id=e.target.dataset.editTransaction;if(id)showTransaction(id);});
$('#showCategoryForm').addEventListener('click',()=>{renderCategoryManager();openDialog('categoryDialog');});$$('[data-open-category]').forEach(b=>b.addEventListener('click',()=>{renderCategoryManager();openDialog('categoryDialog');}));$('#categoryForm').addEventListener('submit',e=>{e.preventDefault();const name=$('#newCategoryName').value.trim();if(!name)return;const type=$('#newCategoryType').value;if(state.categories.some(c=>c.name.toLowerCase()===name.toLowerCase()&&c.type===type)){announce('That category already exists.');return;}state.categories.push({id:uid('cat'),name:name.slice(0,40),type});$('#newCategoryName').value='';localStorage.setItem(STORAGE_KEY,JSON.stringify(state));renderCategoryManager();render();announce('Category added.');});$('#categoryList').addEventListener('click',e=>{const id=e.target.dataset.deleteCategory;if(!id)return;if(confirm('Delete this unused category?')){state.categories=state.categories.filter(c=>c.id!==id);saveState('Category deleted.');renderCategoryManager();}});
$('#budgetRows').addEventListener('change',e=>{const id=e.target.dataset.budgetCategory;if(!id)return;const value=Number(e.target.value);const month=monthKey();state.budgets[month] ||= {};if(!e.target.value||value===0)delete state.budgets[month][id];else if(Number.isFinite(value)&&value>0)state.budgets[month][id]=value;saveState('Monthly budget saved.');});
$('#showGoalForm').addEventListener('click',()=>showGoal());$$('[data-open-goal]').forEach(b=>b.addEventListener('click',()=>showGoal()));$('#goalForm').addEventListener('submit',e=>{e.preventDefault();const id=$('#goalId').value,target=Number($('#goalTarget').value),current=Number($('#goalCurrent').value);if(!Number.isFinite(target)||target<=0||!Number.isFinite(current)||current<0)return announce('Enter a target above zero and a saved amount of zero or more.');const goal={id:id||uid('goal'),name:$('#goalName').value.trim(),target,current};if(id)state.goals=state.goals.map(g=>g.id===id?goal:g);else state.goals.push(goal);closeDialog('goalDialog');saveState(id?'Savings goal updated.':'Savings goal added.');});$('#goalsGrid').addEventListener('click',e=>{if(e.target.dataset.editGoal)showGoal(e.target.dataset.editGoal);if(e.target.dataset.deleteGoal&&confirm('Delete this savings goal?')){state.goals=state.goals.filter(g=>g.id!==e.target.dataset.deleteGoal);saveState('Savings goal deleted.');}});
$('#csvExportButton').addEventListener('click',exportCSV);$('#downloadTemplate').addEventListener('click',()=>download('finflow-csv-template.csv','date,description,amount,category,type\n2026-07-30,Example paycheck,1000.00,Salary,income\n2026-07-30,Example grocery trip,45.50,Groceries,expense\n','text/csv;charset=utf-8'));$('#csvImportButton').addEventListener('click',()=>$('#csvImportInput').click());$('#csvImportInput').addEventListener('change',e=>{if(e.target.files[0])importCSV(e.target.files[0]);});
$('#privacyButton').addEventListener('click',()=>openDialog('privacyDialog'));$('#backupButton').addEventListener('click',()=>openDialog('backupDialog'));$('#jsonExportButton').addEventListener('click',()=>{download(`finflow-backup-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(state,null,2),'application/json');announce('JSON backup downloaded.');});$('#jsonImportInput').addEventListener('change',e=>{if(e.target.files[0])importJSON(e.target.files[0]);});$('#resetButton').addEventListener('click',()=>{const response=prompt('This removes ALL FinFlow data from this browser. Type CLEAR to continue.');if(response==='CLEAR'){localStorage.removeItem(STORAGE_KEY);state=defaultState();closeDialog('backupDialog');render();announce('All FinFlow browser data was cleared.');}else announce('Clear all data canceled.');});
$$('[data-close-dialog]').forEach(button=>button.addEventListener('click',()=>closeDialog(button.dataset.closeDialog)));$$('[data-go-to]').forEach(button=>button.addEventListener('click',()=>document.querySelector(`[data-view="${button.dataset.goTo}"]`).click()));document.addEventListener('keydown',e=>{if(e.key==='Escape')$$('dialog[open]').forEach(d=>d.close());});
render();
